spring:
  application:
    name: spring-boot-example-drools
  disruptor:
    enabled: true
    ring-buffer: true
    ring-buffer-size: 1024
    ring-thread-numbers: 4
    multi-producer: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/siaron_project?currentSchema=drools
    username: siaron_project_admin
    password: siaron_project_admin_pass
    hikari:
      schema: drools
  groovy:
    template:
      check-template-location: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 0
